### ISSUE TITLE
FDR issue on A15 iPhone 13 15.0.1 to 15.4.1

### ISSUE THREAD

**Issue by ashraf008** [marijuanARM/futurerestore#97]
Set nonce using trollnonce. 
Please check the log https://pastelink.net/gib1hkyt 

Using the futurerestore cli mode same issue, FDR error 0/2

**Comment by GiftedK** [comment]
I have the same issue with iPhone 13 Pro Max 15.1.1 to 15.4.1.
`restore_is_current_device: Connected to com.apple.mobile.restored, version 15
Connecting to FDR client at port 1082
About to do ctrl handshake
FDR sending 89 bytes:
FDR Sent 89 bytes
FDR Received 105 bytes
Ctrl handshake done (ConnPort = 49169)
FDR 0x60000293c8a0 waiting for message...
DEBUG: tss_response_get_path_by_entry: No entry 'LLB' in TSS response
NOTE: Could not get LLB path from TSS data, will fetch from build identity
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
Tag found
idevice_event_cb: device 001114923c3a801e (udid: 00008110-001114923C3A801E) disconnected
ERROR: Unable to receive message from FDR 0x60000293c8a0 (-2). 0/2 bytes
FDR 0x60000293c8a0 terminating...
No data to read`

**Comment by HydrationMan** [comment]
> Set nonce using trollnonce. Please check the log https://pastelink.net/gib1hkyt
> 
> Using the futurerestore cli mode same issue, FDR error 0/2

Custom latest doesn't work like that. You're supposed to use --latest-sep and --latest-baseband with it, not manually specify.

**Comment by HydrationMan** [comment]
> I have the same issue with iPhone 13 Pro Max 15.1.1 to 15.4.1.
> `restore_is_current_device: Connected to com.apple.mobile.restored, version 15 Connecting to FDR client at port 1082 About to do ctrl handshake FDR sending 89 bytes: FDR Sent 89 bytes FDR Received 105 bytes Ctrl handshake done (ConnPort = 49169) FDR 0x60000293c8a0 waiting for message... DEBUG: tss_response_get_path_by_entry: No entry 'LLB' in TSS response NOTE: Could not get LLB path from TSS data, will fetch from build identity Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found Tag found idevice_event_cb: device 001114923c3a801e (udid: 00008110-001114923C3A801E) disconnected ERROR: Unable to receive message from FDR 0x60000293c8a0 (-2). 0/2 bytes FDR 0x60000293c8a0 terminating... No data to read`

Please send your full log

**Comment by GiftedK** [comment]
> Please send your full log

Here you go

https://pste.link/g1x60ddi

**Comment by HydrationMan** [comment]
> > Please send your full log
> 
> Here you go
> 
> https://pste.link/g1x60ddi

Use custom-latest-buildid 19H12 and custom-latest-beta instead of manually specifying.

**Comment by GiftedK** [comment]
> Use custom-latest-buildid 19H12 and custom-latest-beta instead of manually specifying.

ERROR: Unable to receive message from FDR 0x60000383c000 (-2). 0/2 bytes

Same issue.

**Comment by Cryptiiiic** [comment]
you need to delete /tmp/futurerestore cache before each run until its fixed in 292 @GiftedK

**Comment by GiftedK** [comment]
> you need to delete /tmp/futurerestore cache before each run until its fixed in 292 @GiftedK

@Cryptiiiic Thanks for your reply, the issue is still persist, even after deleting the cache 

https://pste.link/sozjnc6w

**Comment by Cryptiiiic** [comment]
@GiftedK because you didn't enable no-rsep

**Comment by HydrationMan** [comment]
They're running gui so they probably can't see the option

**Comment by Cryptiiiic** [comment]
frog added it days ago @hydrationMan

**Comment by HydrationMan** [comment]
Forgor💀

**Comment by GiftedK** [comment]
> @GiftedK because you didn't enable no-rsep

@Cryptiiiic Done, and futurerestore succeeded. However, I lost FaceID :(. 15.4.1 with 15.6RC 19G69 SEP+Baseband. I thought it would be better if I want to update to 15.7 later with Delayed OTA method.

https://pste.link/ijoj198d

**Comment by Cryptiiiic** [comment]
@ashraf008 manually specifying sep bb will bootloop. If you restore the correct way with custom latest you will lose faceid anyway. I really don't want to use github issues for support so closing this because its not an issue with the tool itself.

**Comment by joshuaseltzer** [comment]
@Cryptiiiic I hate to bring back an issue you had previously closed, but some questions regarding a situation similar to what was discussed in this issue are going to be more common with people wanting to use futurerestore to upgrade from 15.x to 15.4.1.

Specifically, there seems to be conflicting information regarding whether or not FaceID will break on certain devices when using futurerestore to go from 15.x to 15.4.1 when using `--custom-latest` flag set to 15.7 and enabling the `--no-rsep` option. It sounds like the futurerestore process will indeed succeed, but based on your previous comment, FaceID will no longer work, at least in the case of the iPhone 13 / A15 chip. This contradicts the information in the [SEP Compatibility Spreadsheet](https://docs.google.com/spreadsheets/d/1Mb1UNm6g3yvdQD67M413GYSaJ4uoNhLgpkc7YKi3LBs/). If this is true, then whoever is maintaining that spreadsheet should update the iOS 15.4–15.6.1 column to indicate that using the 15.7 SEP will "Break FaceID" (instead of saying "Compatible").

If you could provide clarification, that would be fantastic. Thanks again for keeping this tool maintained!

**Comment by GiftedK** [comment]
@Cryptiiiic In my case I had my FaceID broken with latest sep of 15.6 "19G69" which seems to use the identical SEP as of 15.7. I've used 15.6 RC SEP "which is still being signed" as I thought it would be better if I want to update to 15.7 later using Delayed OTA method. I will wait and hopefully Fugu15 will be released soon and I will be able to add my nonce and restore again and test.

**Comment by Cryptiiiic** [comment]
@joshuaseltzer first and foremost, rsep should have no affect of the sep installed to the device its literally only for restore mode. Also no-rsep still sends restore sep, it just choses not to run the firmware command in recovery. For some reason that command has been panicing sep on and off since 14.2.

**Comment by joshuaseltzer** [comment]
> @joshuaseltzer first and foremost, rsep should have no affect of the sep installed to the device its literally only for restore mode. Also no-rsep still sends restore sep, it just choses not to run the firmware command in recovery. For some reason that command has been panicing sep on and off since 14.2.

Thanks for the info. I guess this means A15 devices should refrain from using futurerestore on 15.x for now.

**Comment by ghost** [comment]
I've updated the spreadsheet now. I wasn't sure exactly which devices/versions were having trouble before, which is why I hadn't updated it.
